### ISSUE TITLE
Approvazione device

### ISSUE THREAD

**Issue by NataleConsalvi** [NataleConsalvi/homeworktpa-nc#1]
Buongiorno professor @DavidLeoni,
nella repository ho inserito una prima bozza del [device](https://github.com/NataleConsalvi/homeworktpa-nc/blob/main/bozzadevice.svg) che vorrei realizzare, i parametri che vorrei utilizzare sono elencati nel [README.md](https://github.com/NataleConsalvi/homeworktpa-nc/blob/main/README.md).
Le chiedo se la bozza va bene quindi se posso procedere con il lavoro.

Cordiali saluti

**Comment by NataleConsalvi** [comment]
Buona sera professor @DavidLeoni,
ho aggiornato la bozza del [device](https://github.com/NataleConsalvi/homeworktpa-nc/blob/main/bozzadevice.svg).
Le chiedo se le modifiche effettuate soddisfano i requisiti citati oggi pomeriggio.
Cordiali saluti

**Comment by DavidLeoni** [comment]
Metterei l'angolo variabile, così da avere una constraint non banale tra larghezza maniglia e bordo della valigia

**Comment by NataleConsalvi** [comment]
Perfetto professore, aggiungo il parametro
